# Generates src/ui/icons.ts: the Material Icons (Rounded) the app draws, as SVG path data. The same icons the Android app
# uses (Compose's Icons.Rounded), from @material-design-icons/svg, so both apps show the same glyphs.
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
src = os.path.join(root, 'node_modules', '@material-design-icons', 'svg', 'round')

NAMES = '''
laptop dashboard send inventory_2 devices battery_charging_full battery_full battery_alert memory thunderstorm umbrella ac_unit
wb_sunny cloud music_note skip_previous skip_next album lyrics remove add content_paste content_copy language lock
notifications_active mouse desktop_windows cast_connected download check_circle error_outline info system_update photo_camera
public search close cloud_off bolt south north chevron_right storage timer wifi wifi_off bluetooth bluetooth_disabled
airplanemode_active airplanemode_inactive dark_mode light_mode mic_off mic volume_off volume_up pause play_arrow replay home
speed center_focus_strong settings equalizer toggle_on close_fullscreen tune view_agenda palette animation short_text
privacy_tip headphones settings_voice speaker check swap_horiz delete_sweep bedtime restart_alt power_settings_new timer_off
apps clear_all screenshot text_fields description currency_exchange shuffle photo_library folder folder_zip image movie
refresh qr_code_scanner keyboard phone_iphone call wifi_tethering widgets brightness_auto blur_on shield open_in_new history
new_releases visibility visibility_off keyboard_arrow_left keyboard_arrow_right keyboard_arrow_up keyboard_arrow_down
backspace arrow_back zoom_out_map screen_rotation desktop_access_disabled insert_drive_file ios_share face fingerprint
add_to_home_screen delete link key tablet_mac more_horiz auto_awesome picture_in_picture_alt drag_indicator touch_app
edit logout cleaning_services offline_bolt verified_user sync keyboard_command_key content_paste_go front_hand
'''.split()

out = ['// Generated by scripts/icons.py: Material Icons (Rounded), as the Android app draws them. Do not edit.',
       'export const ICONS = {']
missing = []
for name in NAMES:
    p = os.path.join(src, name + '.svg')
    if not os.path.exists(p):
        missing.append(name); continue
    svg = open(p, encoding='utf-8').read()
    body = re.sub(r'^<svg[^>]*>|</svg>\s*$', '', svg.strip())
    # The invisible frames some files carry.
    body = re.sub(r'<path d="M0 0h24v24H0z" fill="none"/>', '', body)
    body = re.sub(r'<path fill="none" d="M0 0h24v24H0z"/>', '', body)
    if '"' in body.replace('="', '').replace('" ', '').replace('"/', ''):
        pass
    out.append("  %s: '%s'," % (re.sub(r'_(\w)', lambda m: m.group(1).upper(), name), body.replace("'", "\\'")))
out.append('} as const;')
out.append('export type IconName = keyof typeof ICONS;')
open(os.path.join(root, 'src', 'ui', 'icons.ts'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('icons:', len(NAMES) - len(missing), 'missing:', ' '.join(missing) or 'none')
